printEval <- function(eval) {
  cat("TPs:", eval$TP, "\n")
  cat("FPs:", eval$FP, "\n")
  cat("FNs:", eval$FN, "\n")
  cat("TNs:", eval$TN, "\n")
  cat("Accuracy:", eval$accuracy, "\n")
  cat("Sensitivity:", eval$sensitivity, "\n")
  cat("Specificity:", eval$specificity, "\n")
  cat("Prevalence:", eval$prevalence, "\n")
  cat("PPV:", eval$PPV, "\n")
  cat("NPV:", eval$NPV, "\n")
  cat("Detection Rate:", eval$detection_rate, "\n")
  cat("Detection Prevalence:", eval$detection_prevalence, "\n")
  cat("Balanced Accuracy:", eval$balanced_accuracy, "\n")
  cat("Precision:", eval$precision, "\n")
  cat("Recall:", eval$recall, "\n")
  cat("F1 Score:", eval$F1, "\n")
}

printEvalComparison <- function(eval1, eval2) {
  cat("TPs difference:", eval1$TP - eval2$TP, "\n")
  cat("FPs difference:", eval1$FP - eval2$FP, "\n")
  cat("FNs difference:", eval1$FN - eval2$FN, "\n")
  cat("TNs difference:", eval1$TN - eval2$TN, "\n")
  cat("Accuracy difference:", eval1$accuracy - eval2$accuracy, "\n")
  cat("Sensitivity difference:", eval1$sensitivity - eval2$sensitivity, "\n")
  cat("Specificity difference:", eval1$specificity - eval2$specificity, "\n")
  cat("Prevalence difference:", eval1$prevalence - eval2$prevalence, "\n")
  cat("PPV difference:", eval1$PPV - eval2$PPV, "\n")
  cat("NPV difference:", eval1$NPV - eval2$NPV, "\n")
  cat("Detection Rate difference:", eval1$detection_rate - eval2$detection_rate, "\n")
  cat("Detection Prevalence difference:", eval1$detection_prevalence - eval2$detection_prevalence, "\n")
  cat("Balanced Accuracy difference:", eval1$balanced_accuracy - eval2$balanced_accuracy, "\n")
  cat("Precision difference:", eval1$precision - eval2$precision, "\n")
  cat("Recall difference:", eval1$recall - eval2$recall, "\n")
  cat("F1 Score difference:", eval1$F1 - eval2$F1, "\n")
}